

services:
  postgres:
    image: postgres:18-alpine3.22
    container_name: skin_sense_postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - skin_sense_data:/var/lib/postgresql/data
    networks:
      - skin_sense_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: skin_sense_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - skin_sense_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  minio:
    image: minio/minio:latest
    container_name: skin_sense_minio
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9000"   # S3 API
      - "${MINIO_CONSOLE_PORT}:9001"  # Web console
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - skin_sense_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  skin_sense_data:
  pgadmin_data:
  minio_data:

networks:
  skin_sense_network:
    driver: bridge

